spring.application.name=baskin

spring.thymeleaf.suffix=.html
spring.thymeleaf.prefix=classpath:/templates/

spring.resources.static-locations=classpath:/static/, classpath:/public/, classpath:/custom-static/