spring:
  application:
    name: kiosk
  datasource:
    url: jdbc:mariadb://localhost:3306/kiosk
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML

server:
  port: 8088

mybatis:
  type-aliases-package: com.example.kiosk.branch,com.example.kiosk.menu,com.example.kiosk.stock,com.example.kiosk.pay
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
