spring:
  application:
    name: kiosk

  datasource:
    url: jdbc:mariadb://tomhoon.duckdns.org:33303/kiosk
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver


  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB

  devtools:
    livereload:
      enabled: true

recaptcha:
  site-key: 6LcxWhwrAAAAAOWzawUK53kcycZg8UmdSDetP8oF
  secret: 6LcxWhwrAAAAADK0jXsxoqJ1_aRjWaELSYgEGvl5

server:
  port: 8080

mybatis:
  type-aliases-package: com.example.kiosk
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

firebase:
  config-path: firebase-service-account.json

custom:
  api-key: test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6

logging:
  level:
    root: info
  dump:
    sql:
      maxlinelength: 0
  drivers: com.mysql.cj.jdbc.Driver
  auto:
    load:
      popular:
        drivers: false
